### ISSUE TITLE
Missing placeholder for empty values

### ISSUE THREAD

**Issue by Ramir1** [deltablot/malle#9]
Use:
`document.querySelectorAll('.control-editable').forEach((elem)=>elem.innerText=(elem.innerText === ''?'--edit--':elem.innerText))`
Thank you!

**Comment by NicolasCARPi** [comment]
Hello,

Would you care to expand your thought? Why do you have empty values and what do you think `malle` could do to improve DX ? The idea is that malle makes an element clickable. If it's empty it is not clickable, or maybe you can replace the empty value with a placeholder such as "Click to edit". I don't really see how this is `malle`'s job to fill the editable element with something.  Maybe you can use the `after` option to add your text if the value is empty?

**Comment by Ramir1** [comment]
![2git](https://github.com/deltablot/malle/assets/971933/77398f7f-8078-48cf-a9d3-213d43271236)

**Comment by NicolasCARPi** [comment]
Thank you for the lovely drawing. But my point is that I don't see this as `malle`'s job. I have the same use case as you:

In a column, sometimes the value is empty because it is an optional value, in this case, the templating system will add `font-italic` class and *unset* as content.

When the *unset* is clicked, it looks like this:

![ezgif com-video-to-gif](https://github.com/deltablot/malle/assets/3043706/2ce2d488-23a0-4336-9079-a02fafbe0dc2)

The code for malle has this:

~~~javascript
onEdit: (original, _, input) => {
      if (original.innerText === 'unset') {
        input.value = '';
        original.classList.remove('font-italic');
      }
      return true;
    },
~~~

So that when the user clicks it, it is no longer in italic and the input is empty. So you see, you can already achieve great user experience and I hope I made my point that no changes to malle code is necessary.

**Comment by Ramir1** [comment]
I offered )) Malle is a wonderful script without it)

**Comment by NicolasCARPi** [comment]
Ok I see, you just wanted to share your code snippet, not make a feature request. Thank you for sharing then!
